import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Physical AI & Humanoid Robotics textbook
  textbookSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'Week 1: Introduction to Physical AI and Humanoid Robotics',
      items: ['chapters/chapter-1-introduction'],
    },
    {
      type: 'category',
      label: 'Week 2: Fundamentals of Robot Operating System (ROS 2)',
      items: ['chapters/chapter-2-ros2-fundamentals'],
    },
    {
      type: 'category',
      label: 'Week 3: Simulation Environments (Gazebo & Unity)',
      items: ['chapters/chapter-3-simulation'],
    },
    {
      type: 'category',
      label: 'Week 4: NVIDIA Isaac Platform and GPU-Accelerated Robotics',
      items: ['chapters/chapter-4-isaac-platform'],
    },
    {
      type: 'category',
      label: 'Week 5: Vision-Language-Action Robotics',
      items: ['chapters/chapter-5-vla-robotics'],
    },
    {
      type: 'category',
      label: 'Week 6: Conversational Robotics and Human-Robot Interaction',
      items: ['chapters/chapter-6-conversational-robotics'],
    },
    {
      type: 'category',
      label: 'Week 7: Hardware Design for Humanoid Robots',
      items: ['chapters/chapter-7-hardware-design'],
    },
    {
      type: 'category',
      label: 'Week 8: Control Systems and Motion Planning',
      items: ['chapters/chapter-8-control-systems'],
    },
    {
      type: 'category',
      label: 'Week 9: AI and Machine Learning for Robotics',
      items: ['chapters/chapter-9-ai-ml-robotics'],
    },
    {
      type: 'category',
      label: 'Week 10-13: Capstone Humanoid Robot Project',
      items: ['chapters/chapter-10-capstone-project'],
    },
  ],
};

export default sidebars;
